# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Setup Keychain & Import Provisioning Profiles"
  lane :setup do
    if is_ci
      setup_ci
    end
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_filepath: ENV['APP_STORE_CONNECT_FILE_PATH'],
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    match(type: "appstore", readonly: is_ci)
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    

    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_filepath: ENV['APP_STORE_CONNECT_FILE_PATH'],
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    upload_to_testflight(
      notify_external_testers: true,
      changelog: ENV['RELEASE_NOTES']
    )
  end
end
